.TH "copycat" 1 "02 May 2022" "" "copycat Documentation"

.SH NAME
copycat \- Intercept system calls

.SH SYNOPSIS
.B copycat
[\-hn] \-\-
.I command

.SH DESCRIPTION

.P
This command intercepts system calls for a program given via the
.I command
argument. This is mostly used to redirect hardcoded files in a binary.

.P
Redirecting rules are defined via the
.I COPYCAT
environment variable. For example to redirect all system calls accessing /tmp/a.txt to /tmp/b.txt, you would use
.I COPYCAT="/tmp/a.txt /tmp/b.txt"
to redirect them without needing to do any change to the binary.

.TP
.B \-h
Show usage information.

.TP
.B \-n
Do not use seccomp, but an alternative
.I LD_PRELOAD
implementation to intercept system calls. This alternative implementation has minimal performance impact, but does not work with all binaries, thus this option is disabled by default.
Example binaries that do not work with this method include statically linked binaries and binaries that call system calls directly instead of through the libc interface.

.SH EXIT STATUS
The exit status will be passed through from the supervised process.

.SH EXAMPLES
The following example tricks cat into opening a different file than was given.
.PP
.in +2n
.EX
$ COPYCAT="/tmp/a.txt /tmp/b.txt" \fBcopycat\fP \-\- cat /tmp/a.txt
.EE
.in
.PP

.SH HOMEPAGE
https://github.com/vimpostor/copycat

Please report bugs and feature requests in the issue tracker.
