name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        cxx: [g++, clang++]
    runs-on: ubuntu-latest
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y libseccomp-dev
    - name: Configure the project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - name: Build the project
      run: cmake --build build
      # Reenable tests once we have figured out how to run with permissions in CI (probably need to remove the fork mechanism)
    # - name: Run tests
      # run: tests/run-tests.sh
